include:
  - docker-compose.base.yml
services:
  signals-redis:
    image: redis:7-bookworm
    command: redis-server --requirepass "redis"
    restart: unless-stopped
    volumes:
      - redis-signals:/data/redis

  # signals-silo:
  #   image: ghcr.io/civitai/civitai-signals-silo:latest
  #   depends_on:
  #     - signals-redis
  #   environment:
  #     ConnectionStrings__Redis: signals-redis:6379,password=redis

  # signals-api:
  #   image: ghcr.io/civitai/civitai-signals-api:latest
  #   depends_on:
  #     - signals-silo
  #   ports:
  #     - "9050:8080"
  #   environment:
  #     ConnectionStrings__Redis: signals-redis:6379,password=redis
  #     ConnectionStrings__Silo: signals-silo:5000

  # buzz:
  #   image: ghcr.io/civitai/civitai-buzz:latest
  #   ports:
  #     - "9051:8080"
  #   environment:
  #     ConnectionStrings__BuzzDbContext: Host=civitai-db;Port=5432;Database=buzz;Username=postgres;Password=postgres
  #     SignalApiClient__Endpoint: http://signals-api:8080
  #     ClickhouseTrackerApiClient__Endpoint: http://localhost:9911
  civitai-db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: civitai
      POSTGRES_PASSWORD: civitai
      POSTGRES_DB: civitai
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  redis-signals:
  pgdata:
